name: app_admin
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 2.0.2+9

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  flutter_svg: ^2.0.5
  google_fonts: ^4.0.4
  cloud_firestore: ^4.7.0
  firebase_core: ^2.12.0
  rounded_loading_button: ^2.1.0
  ionicons: ^0.2.1
  line_icons: ^2.0.1
  html_editor_enhanced: ^2.5.1
  pointer_interceptor: ^0.9.3+4
  youtube_parser: ^2.1.1
  firebase_auth: ^4.6.0
  data_table_2: ^2.5.8
  firebase_ui_firestore: ^1.5.0
  cached_network_image: ^3.3.0
  intl: ^0.18.0
  shared_preferences: ^2.1.1
  url_strategy: ^0.2.0
  image_picker: ^0.8.7+5
  firebase_storage: ^11.2.0
  dotted_border: ^2.0.0+3
  file_picker: ^5.3.0
  url_launcher: ^6.1.11
  http: ^0.13.4
  loading_animation_widget: ^1.2.0+4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/user_avatars/




